//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOHangHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMHang
    {
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGiaNhap { get; set; }
        public Nullable<decimal> DonGiaBan { get; set; }
        public string Hinh { get; set; }
        public string GhiChu { get; set; }
        public string MaCLieu { get; set; }
    
        public virtual DMChatLieu DMChatLieu { get; set; }
    }
}
